# Generated by Django 3.1.7 on 2021-03-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название картинки')),
                ('img', models.ImageField(blank=True, upload_to='images/', verbose_name='Картинка')),
            ],
        ),
    ]
